// Code generated by mockery v2.12.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/julioshinoda/port/entity"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// PortRepository is an autogenerated mock type for the PortRepository type
type PortRepository struct {
	mock.Mock
}

// Upsert provides a mock function with given fields: ctx, port
func (_m *PortRepository) Upsert(ctx context.Context, port entity.Port) error {
	ret := _m.Called(ctx, port)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Port) error); ok {
		r0 = rf(ctx, port)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPortRepository creates a new instance of PortRepository. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewPortRepository(t testing.TB) *PortRepository {
	mock := &PortRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
